#!/usr/bin/env python

import tomllib
import os
import sys
import pathlib
import subprocess
import re

THIS_FILE_DIR = os.path.dirname(os.path.abspath(__file__))
CARGO_TOML_FILE = os.path.join(THIS_FILE_DIR, "Cargo.toml")
CARGO_TOML_FILE_NEW = os.path.join(THIS_FILE_DIR, "Cargo.toml.new")


def main():
    day_num = int(sys.argv[1])
    day_crate = f"day-{day_num:02}"

    crate_path = os.path.join(THIS_FILE_DIR, "crates", day_crate)
    # relative path
    crate_rel_path = os.path.relpath(crate_path, THIS_FILE_DIR)
    print(crate_rel_path)

    if not os.path.exists(crate_path):
        subprocess.run(["cargo", "new", crate_rel_path], check=True)

    new_cargo_toml_contents = None
    with open(CARGO_TOML_FILE, "r") as f:
        cargo_toml_contents = f.read()
        if crate_rel_path not in cargo_toml_contents:
            new_cargo_toml_contents = re.sub(
                ",\n]", f',\n    "{crate_rel_path}",\n]', cargo_toml_contents
            )

    if new_cargo_toml_contents:
        with open(CARGO_TOML_FILE, "w") as f:
            f.write(new_cargo_toml_contents)


if __name__ == "__main__":
    main()
